-- Update avatar image URLs to AI-generated references
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/ana-reference.jpg' WHERE id = '4c6fa363-e4db-4eb4-98d6-4a028f0f35cf';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/bianca-reference.jpg' WHERE id = '024ac2a9-97e5-44c8-b0cc-87947297a384';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/camila-reference.jpg' WHERE id = 'e1615c00-75b9-4a91-8952-cfd50b4f564b';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/carlos-reference.jpg' WHERE id = 'bd63e8c4-f31b-4367-a54b-85fa67a66ff6';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/diego-reference.jpg' WHERE id = 'c81948f4-aba8-406e-b1b2-a87f7d30a95e';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/fernanda-reference.jpg' WHERE id = '9765fc0a-211d-4c07-aab8-90798b80df53';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/isabela-reference.jpg' WHERE id = '08c34e47-41b4-45d3-89de-d12a77ef3891';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/julia-reference.jpg' WHERE id = '6713f7d1-9fc4-4567-9aa1-14b4a3a28b65';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/lucas-reference.jpg' WHERE id = '5c824355-bf5d-4a96-ac0a-c6892d532d1a';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/maria-reference.jpg' WHERE id = 'e3f63a1a-8c0e-47d9-b1cb-3b40361e1b50';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/pedro-reference.jpg' WHERE id = '905bfb1b-bdf3-4103-b748-2ddb5248b708';
UPDATE avatars SET image_url = 'https://cozy-companion-glow.lovable.app/avatars/rafael-reference.jpg' WHERE id = 'f4ec0536-dab7-4409-8f7d-27545e9ddd5f';

-- Add new scenarios with rich environment_prompt and lighting_defaults
INSERT INTO scenarios (name, prompt_modifier, environment_prompt, lighting_defaults, composition_defaults, negative_drift_prompt, is_active) VALUES
('Café Aconchegante', 'cozy coffee shop interior with warm ambient lighting', 'inside a charming artisan coffee shop with exposed brick walls, warm wooden tables, steaming coffee cups visible, vintage pendant lights hanging from ceiling, cozy intimate atmosphere with soft warm tones, rustic chic decor', '{"type": "warm ambient", "color_temp": "3200K", "intensity": "soft", "source": "pendant lights and window", "mood": "cozy inviting"}', '{"framing": "medium close-up", "angle": "eye level", "depth": "shallow with blurred background", "rule": "rule of thirds"}', 'no harsh fluorescent lighting, no empty sterile space, no fast food restaurant', true),

('Jardim Botânico', 'lush botanical garden with natural sunlight filtering through leaves', 'in a beautiful tropical botanical garden with lush green foliage everywhere, exotic flowers in bloom, dappled sunlight filtering through large tropical leaves, stone pathway visible, rich saturated natural greens, paradise garden atmosphere', '{"type": "dappled natural", "color_temp": "5500K", "intensity": "bright filtered", "source": "sunlight through canopy", "mood": "fresh vibrant natural"}', '{"framing": "medium shot", "angle": "slightly low", "depth": "layered foliage foreground and background", "rule": "natural framing with leaves"}', 'no artificial plants, no indoor greenhouse, no dead vegetation', true),

('Escritório Moderno', 'sleek modern office with floor-to-ceiling windows and city view', 'in a luxurious modern office space with floor-to-ceiling glass windows showing city skyline, minimalist desk setup with MacBook, ergonomic chair, indoor plants, clean contemporary design with concrete and glass elements, professional corporate atmosphere', '{"type": "natural office", "color_temp": "5000K", "intensity": "bright even", "source": "large windows with city view", "mood": "professional productive"}', '{"framing": "medium shot", "angle": "eye level", "depth": "city skyline bokeh in background", "rule": "centered subject"}', 'no cluttered desk, no dark dingy office, no cubicle farm', true),

('Piscina Resort', 'luxury resort pool area with turquoise water and tropical setting', 'at a stunning luxury resort infinity pool with crystal clear turquoise water, white marble pool deck, tropical palm trees and lush landscaping, blue sky with scattered clouds, luxury lounge chairs with white cushions, vacation paradise atmosphere', '{"type": "bright tropical", "color_temp": "6500K", "intensity": "bright direct", "source": "overhead tropical sun", "mood": "luxurious vacation"}', '{"framing": "medium to wide", "angle": "eye level", "depth": "pool and landscape stretching to horizon", "rule": "leading lines from pool edge"}', 'no crowded public pool, no dirty water, no construction', true),

('Varanda ao Pôr do Sol', 'beautiful balcony terrace at golden hour sunset', 'on a spacious modern balcony terrace with elegant outdoor furniture, overlooking a stunning sunset with warm orange and pink sky, city or ocean panorama visible in background, string lights and candles adding warm glow, romantic golden hour atmosphere, glass railing', '{"type": "golden hour", "color_temp": "3500K", "intensity": "warm directional", "source": "setting sun from horizon", "mood": "romantic warm magical"}', '{"framing": "medium shot", "angle": "slightly elevated", "depth": "sunset panorama in deep background", "rule": "subject silhouetted against warm sky"}', 'no harsh midday sun, no rain, no dark nighttime', true),

('Academia Fitness', 'modern gym interior with professional equipment', 'inside a modern premium fitness gym with professional equipment, clean mirrors reflecting the space, rubber flooring, dumbbells and weight racks organized neatly, motivational atmosphere, LED strip lighting accents, contemporary industrial design with exposed ductwork', '{"type": "bright gym", "color_temp": "4500K", "intensity": "bright even", "source": "overhead LED panels and strip lighting", "mood": "energetic motivational"}', '{"framing": "medium shot", "angle": "slightly low heroic", "depth": "gym equipment in soft background", "rule": "dynamic angle"}', 'no dirty gym, no crowded space, no old rusty equipment', true),

('Cozinha Gourmet', 'upscale modern kitchen with marble countertops and premium appliances', 'in a beautiful gourmet kitchen with white marble island countertop, premium stainless steel appliances, fresh herbs and colorful ingredients visible, modern pendant lights above island, warm natural light from kitchen window, clean organized culinary workspace', '{"type": "kitchen natural", "color_temp": "4500K", "intensity": "bright warm", "source": "pendant lights and window light", "mood": "warm culinary inviting"}', '{"framing": "medium close-up", "angle": "eye level across island", "depth": "kitchen depth with blurred background", "rule": "rule of thirds with countertop leading line"}', 'no dirty dishes, no cluttered messy kitchen, no dark space', true),

('Parque Urbano', 'city park with green trees and walking paths', 'in a beautiful urban city park with mature green trees, well-maintained grass lawn, paved walking path, park benches visible, joggers and nature in background, bright sunny day with blue sky, peaceful outdoor urban oasis atmosphere', '{"type": "outdoor natural", "color_temp": "5500K", "intensity": "bright with tree shadows", "source": "natural sunlight with partial shade", "mood": "relaxed outdoor fresh"}', '{"framing": "medium to wide", "angle": "eye level", "depth": "park path leading into distance", "rule": "leading lines with pathway"}', 'no rainy weather, no empty desolate park, no night scene', true);
