
INSERT INTO presets (label, value, type, is_active) VALUES
('Esportivo', 'sporty', 'style', true),
('Elegante', 'elegant', 'style', true),
('Minimalista', 'minimalist', 'style', true),
('Streetwear', 'streetwear', 'style', true),
('Boho', 'boho', 'style', true),
('Suave', 'soft', 'style', true),
('Colorido', 'colorful', 'style', true),
('Verão', 'summer', 'style', true),
('Trendy', 'trendy', 'style', true),
('Básico', 'basic', 'style', true),
('Skin Enhancer', 'skin_enhancer', 'enhancement', true),
('Luz Ambiente', 'ambient_light', 'enhancement', true),
('Ultra Nitidez', 'ultra_sharpness', 'enhancement', true),
('Anti-IA', 'anti_ai', 'enhancement', true),
('Bokeh Pro', 'bokeh_pro', 'enhancement', true),
('Mãos Perfeitas', 'perfect_hands', 'enhancement', true),
('Cabelo Real', 'real_hair', 'enhancement', true),
('Tecido Real', 'real_fabric', 'enhancement', true),
('Brilho Natural', 'natural_glow', 'enhancement', true),
('Vertical', 'vertical', 'format', true),
('Quadrado', 'square', 'format', true),
('Retrato', 'portrait', 'format', true),
('Horizontal', 'horizontal', 'format', true),
('De Frente', 'front_facing', 'pose', true),
('Sentada', 'sitting', 'pose', true),
('Só Produto', 'product_only', 'pose', true);
